### ISSUE TITLE
SmaCC fails to load in Pharo7

### ISSUE THREAD

**Issue by vojtechbalik** [SmaCCRefactoring/SmaCC#58]
![pharoscreenshot 1](https://user-images.githubusercontent.com/36707706/53169222-f0c48900-35dc-11e9-937b-1370d7a3125b.png)

after this, the loading is stuck

**Comment by ThierryGoubier** [comment]
Hi, it's corrected normally; can you retry?

I would suggest you switch to the pharo7 branch for now; the SmaCC debugger in the master branch doesn't work (and lock the image) in Pharo 7.

**Comment by ToshRaka** [comment]
The issue came from an non-escaped quote. Should be fixed now!

**Comment by vojtechbalik** [comment]
@ThierryGoubier I tried running the loading script again, but that failed the same.

@ToshRaka It's fixed now, both master and pharo7 branches load fine. Thanks!

**Comment by ThierryGoubier** [comment]
Fixed by 308d646
